version: '3.8'
services:
  app:
    image: golang:1.21-alpine
    ports:
      - '8080:8080'
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=quivra
      - DB_PASSWORD=password
      - DB_NAME=quivra
    depends_on:
      - mysql
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "go mod tidy && go run main.go"

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: quivra
      MYSQL_USER: quivra
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
      LANG: C.UTF-8
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/migrations.sql:/docker-entrypoint-initdb.d/01-migrations.sql
      - ./database/sample_data.sql:/docker-entrypoint-initdb.d/02-sample_data.sql

volumes:
  mysql_data:
